### ISSUE TITLE
Exception in plaintext formatter

### ISSUE THREAD

**Issue by Craeckie** [tvdstaaij/telegram-history-dump#79]
When using the plaintext formatter I get the following exception:

```
I, [2017-03-30T16:00:57.178394 #226]  INFO -- : Formatting messages
/root/tgh/lib/util.rb:11:in `get_full_name': undefined method `[]' for nil:NilClass (NoMethodError)
        from /root/tgh/formatters/plaintext.rb:53:in `format_message'
        from /root/tgh/formatters/lib/daily_file_formatter.rb:37:in `block in format_dialog'
        from /root/tgh/formatters/lib/daily_file_formatter.rb:21:in `reverse_each'
        from /root/tgh/formatters/lib/daily_file_formatter.rb:21:in `format_dialog'
        from /root/tgh/telegram-history-dump.rb:389:in `block (2 levels) in <main>'
        from /root/tgh/telegram-history-dump.rb:388:in `each'
        from /root/tgh/telegram-history-dump.rb:388:in `block in <main>'
        from /root/tgh/telegram-history-dump.rb:381:in `each'
        from /root/tgh/telegram-history-dump.rb:381:in `<main>'
```
The HTML formatter works.

Here's my config:
[config.yaml](https://github.com/tvdstaaij/telegram-history-dump/files/882576/config.txt)

**Comment by Hjdskes** [comment]
Can confirm, just got this as well!

**Comment by tvdstaaij** [comment]
Thanks for the report. This is a regression in 2.4.0, introduced by 4cecd8e, with bad timing as I couldn't work on Github projects for some time. The function was supposed return an empty string in return to a nil argument, but this behavior got lost in the rewrite. Fixed in 2.4.1 through f45549c.
